version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: nest-db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    networks:
      - Heepoke

volumes:
  redis-data:

networks:
  Heepoke:
    driver: bridge
