export const ServiceConstants = {
  NAME_SERVICE: 'Api Queue',
  APP_SERVICE: 'APP SERVICE',
  AUTH_SERVICE: 'AUTH SERVICE',
  QUEUE_SERVICE: 'QUEUE SERVICE',
  QUEUE_LOGS_SERVICE: 'QUEUE LOGS SERVICE',
  QUEUE_REWARD_SERVICE: 'QUEUE REWARD SERVICE',
  USER_SERVICE: 'USER SERVICE',
  REWARD_SERVICE: 'REWARD SERVICE',
  CSV_SERVICE: 'CSV SERVICE',
  SCHEDULE_SERVICE: 'SCHEDULE SERVICE',
  UTILITIES_SERVICE: 'UTILITIES_SERVICE',
};

export const DescriptionConstants = {
  APP_DESCRIPTION: '----',
  HEALTH_DESCRIPTION: 'health of queue service',
  AUTH_TOKEN_FAILED: 'token expired or invalid',
  AUTH_AUTO_LOGIN: 'automatic login success',
  AUTH_AUTO_LOGIN_FAILED: 'automatic login failed',
  GET_LIST_QUEUE_DESCRIPTION: 'get list queue',
  CREATE_QUEUE_DESCRIPTION: 'create queue',
  CHECK_STATUS_QUEUE_DESCRIPTION: 'check status queue',
  GET_LIST_USERS: 'get list users',
  GET_LIST_USERS_FAILED: 'get list users failed',
  GET_USER_BY_EMAIL: 'get user by email',
  GET_USER_BY_EMAIL_FAILED: 'get user by email failed',
  CHECK_POINTS_USER: 'check points user',
  CHECK_POINTS_USER_FAILED: 'check points user failed',
  GET_LIST_REWARDS: 'get list rewards',
  GET_REWARDS_FAILED: 'get list rewards failed',
  GET_LIST_REWARD_TICKETS: 'get list reward tickets',
  GET_REWARD_TICKETS_FAILED: 'get list reward tickets failed',
  FIND_REWARD_BY_ID: 'find reward by id',
  FIND_REWARD_BY_ID_FAILED: 'find reward by id failed',
  GIVE_REWARD_FAILED: 'give reward failed',
  GIVE_REWARD: 'give reward success',
  GET_KEY_SUCCESS: 'get key success',
  GET_KEY_FAILED: 'get key failed',
  SET_KEY_SUCCESS: 'set key success',
  SET_KEY_FAILED: 'set key failed',
  DEL_KEY_SUCCESS: 'delete key success',
  DEL_KEY_FAILED: 'delete key failed',
  GET_LIST_QUEUE_LOGS: 'get list queue logs',
  GET_LIST_QUEUE_LOGS_FAILED: 'get list queue logs failed',
  CHECK_USER_FROM_QUEUE_LOGS: 'check user from queue logs',
  CHECK_USER_FROM_QUEUE_LOGS_FAILED: 'check user from queue logs failed',
  GENERATE_USER: 'generate user success',
  GENERATE_USER_FAILED: 'generate user failed',
  GENERATE_USER_POINTS: 'generate user success',
  GENERATE_USER_POINTS_FAILED: 'generate user failed',
  GET_REWARD_REDEMPTION_SUCCESS: 'get reward redemption success',
  GET_REWARD_REDEMPTION_FAILED: 'get reward redemption failed',
  GET_USER_POINT: 'get user points',
  NOT_HAVE_POINT_USER: 'not have point user',
  UPDATE_POINT_USER_SUCCESS: 'update point user success',
  CREATE_USER_SUCCESS: 'create user success',
  CREATE_USER_POINT_SUCCESS: 'create user point success',
  CREATE_USER_ROLE_SUCCESS: 'create user role success',
  SET_CACHE_SUCCESS: 'set cache success',
  GET_CACHE_SUCCESS: 'get cache success',
  DELETE_CACHE_SUCCESS: 'delete cache success',
  CAN_NOT_FOUND_DATA_TO_UPDATE: 'can not find data to update',
  NOT_HAVE_FILE_CREATE: 'not have create file',
  SCHEDULE_CREATE_FILE_DAILY_FAILED: 'create file daily failed',
  NOT_FOUND_FILE: 'not found file',
  NOT_HAVE_UPDATE_REWARD: 'No rewards update data.',
  USER_NOT_FOUND: 'user not found',
  CREATE_CSV: 'create csv success',
  CREATE_CSV_FAILED: 'create csv failed',
  DELETE_FILE_CSV: 'delete file csv success',
  DELETE_FILE_CSV_FAILED: 'delete file csv failed',
  GET_USER_FORMAT_TEST: 'get users format for test',
  GET_USER_FORMAT_TEST_FAILED: 'get users format for test failed',
  REWARD_NOT_FOUND: 'reward not found',
  AUTH_LOGIN_SUCCESS: 'login success',
  AUTH_LOGIN_FAILED: 'login failed',
  AUTH_PASSWORD_NOT_MATCH: 'password not match',
  QUEUE_LOG_REWARD: 'queue log reward success',
  QUEUE_LOG_REWARD_FAILED: 'queue log reward failed',
  UPDATE_REWARD_DAILY: 'update reward daily success',
  UPDATE_REWARD_DAILY_FAILED: 'update reward daily failed',
};

export const MessageConstants = {
  GET_REWARD_REDEMPTION_SUCCESS: 'แลกของรางวัลสำเร็จแล้ว',
};

export const ErrorMessage = {
  ERROR_SYSTEM: 'ระบบมีปัญหากรุณาติดต่อผู้ดูแล',
  ERROR_NOT_FOUND_USER: 'ไม่พบข้อมูลผู้ใช้',
  ERROR_NOT_ENOUGH_POINTS: 'Points ไม่เพียงพอ',
  ERROR_EXCHANGE_EXPIRED: 'หมดสิทธิ์ในการแลกแล้ว',
  ERROR_NOT_USE_POINTS: 'ไม่สามารถหัก Points ได้',
  ERROR_TRY_AGAIN_REWARD:
    'ทำรายการไม่สำเร็จ กรุณาทำรายการใหม่อีกครั้ง หรือ ตรวจสอบ My Reward',
  ERROR_CANNOT_GET_REWARD_TICKET_DATA: 'can not get reward ticket status',
  ERROR_CANNOT_CHECK_REDEMPTIONS_STATUS: 'can not check redemptions status',
};
